name: Custom Badge Status

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  custom_job_1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Your Custom Step 1
        id: custom_step_1
        run: |
          ref=1
          if [[ ${{ github.ref }} == *1* ]]; then
            v=$(echo ${{ github.ref }} | cut -d'/' -f3)
            echo "version tag is ${v}"
            ref=2
          else
            echo "There is no github tag reference, skipping ${{ ref }}"
          fi