name: Custom Badge Status

on:
  push:
    branches:
      - main
  workflow_dispatch:
    debug: true

jobs:
  custom_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Your Custom Step
        id: custom_step
        run: |
          # Your custom script or command here
          # Example:
          if [ "$SOME_CONDITION_1" == "true" ]; then
            echo "Custom Job Failed"
            exit 1  # Set a non-zero exit status to indicate failure
          else
            echo "job-status=${{ steps.get_custom_job_status.outputs.job-status }}" >> $GITHUB_ENV
          fi

      - name: Set Badge Status
        run: |
          if [ "$job-status" == "success" ]; then
            echo "::set-output name=badge::success"
          else
            echo "::set-output name=badge::failure"
          fi

    outputs:
      badge: ${{ steps.set_badge_status.outputs.badge }}