name: Custom Badge Status

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  custom_job_1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Your Custom Step 1
        id: custom_step_1
        run: |
          # Your custom script or command here
          # Example:
          if [ "$SOME_CONDITION_1" = "true" ]; then
            echo "Custom Job 1 Failed"
            exit 1  # Set a non-zero exit status to indicate failure
          else
            echo "job-status=${{ steps.get_custom_job_1_status.outputs.job-status }}" >> $GITHUB_ENV
          fi

  custom_job_2:
    runs-on: ubuntu-latest
    needs: custom_job_1
    if: ${{  }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Your Custom Step 2
        run: |
          # Your custom script or command here
          # Example:
          echo "Running Custom Job 2 even if Custom Job 1 failed ${{ needs.custom_job_1.outputs.job-status }}"
