name: Compare Strings

on:
  push:
    branches:
      - main

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compare Strings
        run: |
          string1="Hello"
          string2="Hello"

          if [ "$string1" = "$string2" ]; then
            echo "The strings are equal."
          else
            echo "The strings are not equal."
          fi
