name: Compare Strings with Retry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compare Strings
        run: |
          attempt=1
          max_attempts=3

          while [ $attempt -le $max_attempts ]; do
            string1="Hello"
            string2="World"

            if [ "$string1" != "$string2" ]; then
              echo "The strings are equal."
              break  # Break out of the loop if the comparison succeeds
            else
              echo "Attempt $attempt failed."
              attempt=$((attempt+1))
            fi

            if [ $attempt -gt $max_attempts ]; then
              echo "All attempts failed."
            fi
          done
