name: Custom Badge Status

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  custom_combined_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Your Custom Step 1
        id: custom_step_1
        run: |
          # Your custom script or command here for custom_job_1
          # Example:
          if [ "$SOME_CONDITION_1" != "true" ]; then
            echo "Custom Job 1 Failed"
            echo "job-status=failure" >> $GITHUB_ENV
          else
            echo "job-status=success" >> $GITHUB_ENV
          fi

      - name: Your Custom Step 2 (Conditional)
        if: ${{ always() && steps.custom_step_1.outputs.job-status == 'success' }}
        run: |
          # Your custom script or command here for custom_job_2
          # Example:
          echo "Running Custom Job 2 since Custom Job 1 succeeded"
