name: Custom Badge Status

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  var: 1
jobs:
  custom_job_1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Your Custom Step 1
        id: custom_job_1
        run: |
          if [ "$var" != 1 ]; then
            # Increment the variable by +1
            var=$((var+1))
            echo "var is equal to 1"
          else
            echo "var is not equal to 1, failing the job"
            exit 1  # Exiting with a non-zero status to indicate failure
          fi
          
          # Output the status to be used in the next step
          # echo "::set-output name=status::${var}"

      - name: Show Status Badge
        if: ${{ always() && "$var" == 1 }}
        continue-on-error: false
        run: |
          echo "Status: Pass $var"
          if [ "$var" == 1 ]; then
            # Increment the variable by +1
            var=$((var+1))
            echo "var is equal to 1"
            echo "::set-output name=status::${var}"
          else
            echo "var is not equal to 1, failing the job"
            exit 1  # Exiting with a non-zero status to indicate failure
          fi
          # Add code here to display a badge for passing status