name: Custom Badge Status

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  custom_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Your Custom Step 1
        id: custom_step_1
        env:
          var: 1
        run: |
          if [ "$var" -eq 2 ]; then
            # Increment the variable by +1
            var=$((var+1))
            echo "var is equal to 1"
            echo "::set-output name=status::pass" # Set a custom output named 'status' to 'pass'
          else
            echo "var is not equal to 1, failing the job"
            echo "{status}={fail}" >> $GITHUB_OUTPUT # Set a custom output named 'status' to 'fail'
            exit 1  # Exiting with a non-zero status to indicate failure
          fi

      - name: Show Status Badge
        if: ${{ always() && steps.custom_step_1.outputs.status == 'pass' }}
        run: |
          echo "Status: Pass"
          # Add code here to display a badge for passing status

      - name: Show Else Message
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        if: ${{ always() && steps.custom_step_1.outputs.status == 'fail' }}
        run: |
          echo "Else Message: Status not equal to 1"
          echo "::set-env name=CUSTOM_STATUS::pass" # Set a custom environment variable named 'CUSTOM_STATUS' to 'pass'
