name: Custom Badge Status

on:
  push:
    branches:
      - main
   workflow_dispatch:
   
jobs:
  custom_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Your Custom Step
        run: |
          # Your custom script or command here
          # Set the exit status based on your condition
          # Example:
          if [ "$SOME_CONDITION" = "true" ]; then
            echo "Custom Job Succeeded"
            exit 0  # Set the exit status to 0 for success
          else
            echo "Custom Job Failed"
            exit 1  # Set the exit status to 1 for failure
          fi

      - name: Update Job Outcome
        id: job-status
        run: echo "Job Status: ${{ job.status }}" >> $GITHUB_ENV

  display_job_status:
    needs: custom_job
    runs-on: ubuntu-latest
    steps:
      - name: Check Job Outcome
        run: echo "Job Outcome: ${{ needs.custom_job.outputs.job-status }}"  # Access the custom_job's outcome using the output
