name: Custom Badge Status

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  custom_job_1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Your Custom Step 1
        id: custom_step_1
        env:
          var: 1
        run: |
          echo variable is $var
          